# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20161001_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='updated_at',
        ),
    ]
